[package]
name = "shortrest"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
mime_guess = "2.0.5"
rust-embed = "8.7.2"
tokio = { version = "1.47.1", features = ["full"] }
tower-http = { version = "0.6.6", features = ["fs"] }
webbrowser = "1.0.5"
